<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ asset('img/logos sama/logosama.jpg') }}">
    <title>Privacidad | {{ config('app.name', 'Laravel') }}</title>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('/style/empresa/privacidad.css') }}">

</head>

<body>

    <x-header />
    <x-headersama /> 
    <x-nav />

    <div class="privacidad">
        <h2>Políticas de Privacidad y RGPD</h2>
    </div>

    <div id="politicas-privacidad">
        <h3>POLÍTICAS DE PRIVACIDAD</h3>

        <p>En cumplimiento con lo dispuesto en la normativa de protección de datos (Reglamento UE 2016/679, de 27 de abril de 2016), Subministres Sama, Sl (en adelante, "El Titular"), Titular del sitio web www.subministressama.es, (en adelante, el “Sitio Web”), establece la siguiente Política de Privacidad, que seguirá en el tratamiento de datos de carácter personal. Dicha política se entiende, en todo caso, sin perjuicio de los dispuesto en el correspondiente Aviso Legal y en la correspondiente Política de Cookies.</p><br>
        <p><b>1.- Responsable del Tratamiento</b></p><br>
        <p><b>Responsable del Tratamiento:</b> Subministres Sama Sl</p><br>
        <p><b>Dirección:</b> Avda.Constitución,77</p><br>
        <p><b>Email:</b> info@subministressama.es</p><br>
        <p><b>Teléfono:</b> 931050559</p><br>
        <p>Los datos que pudieran solicitarse a los usuarios del presente Sitio Web a través de formularios de contacto, aquellas otras proporcionadas por el mero hecho de acceder al Sitio Web (cookies), aquellos otros relacionados con los posibles comentarios en las distintas páginas corporativas de las redes sociales enlazadas desde el presente Sitio Web, los datos personales que el usuario introduzca dentro de las secciones habilitadas o los proporcionados por el resto de vías o canales de comunicación habilitados (por ejemplo, correo electrónico) serán tratados por el responsable del tratamiento indicado.</p><br>
        <p><b>2.- Finalidades del tratamiento</b></p><br>
        <p>Depende del tratamiento de datos realizado:</p><br>
        <p>-Por el mero hecho de visitar el Sitio Web, existen determinadas informaciones que se recoge en los servidores que prestan servicios de hosting. Entre dichas informaciones está la relativa a la dirección IP desde la que se accede al Sitio Web. La finalidad del tratamiento en este caso es facilitarle la navegación por la web. También podremos recoger determinada información (cookies), que trataremos según la Política de Cookies específica que puede consultar.</p><br>
        <p>-Si nos proporciona los datos a través de alguno o algunos de los formularios habilitados, la finalidad será la relativa a la indicada en el formulario correspondiente. Por ejemplo, en el caso de proporcionarnos sus datos en formularios de contacto, la finalidad será responder en su caso a la consulta realizada.</p><br>
        <p>-Si nos proporciona información a través de alguna o algunas de las redes sociales que esta entidad mantiene y que están enlazadas a través del presente Sitio Web, asumiendo esta entidad la figura de Responsable del Tratamiento de los datos aportados (por ejemplo, fotos subidas por nosotros o por terceros, comentarios que el interesado realice en relación a publicaciones que hagamos, etc), trataremos la información exclusivamente en relación a su consulta, gestión o comentario realizado, y siempre dentro de la red social y en el contexto de la misma, no procediéndose en ningún caso a la extracción de esos datos salvo que obtengamos consentimiento para ello por parte del interesado. No obstante, el uso de estas plataformas está sujeto a la aceptación íntegra de sus condiciones, y ello implica el tratamiento de sus datos con otras condiciones distintas a las aquí expuestas. Los perfiles oficiales en las redes sociales enlazadas desde este Sitio Web han sido creados para que conozca mejor nuestra actividad y crear un canal alternativo de comunicación con las personas interesadas por nuestra entidad y los servicios que ofrecemos, pero declinamos la responsabilidad del tratamiento de datos que las empresas que gestionan las mencionadas redes sociales hagan de los mismos.  </p><br>
        <p>-Si nos proporciona datos personales a través de correo electrónico o a través de otros medios (tradicionales o no), en general trataremos sus datos en relación a la gestión o consulta realizada. En cumplimiento con la Ley 34/2002, de Servicios de la Sociedad de la Información y Comercio Electrónico El titular no remitirá comunicaciones comerciales sin identificarlas como tales y sin una previa información al respecto. A estos efectos no será considerado como comunicación comercial toda la información que se envíe a los interesados siempre que tenga por finalidad el mantenimiento de la relación contractual o respuesta ante su solicitud o aquellas otras informaciones relacionadas con su solicitud -en su caso- y que se deriven directamente de esta relación.</p><br>
        <p>-Si nos realiza algún pedido a través de nuestra tienda virtual, la finalidad será la relacionada con la gestión de clientes, gestión de cobros y pagos, así como el procesamiento y envío del servicio/producto a la dirección indicada. También podríamos utilizarlos en relación al envío de comunicados comerciales (también en relación a la suscripción de la newsletter, en caso de previo consentimiento).</p><br>
        <p>-Si nos da su autorización, podemos tratar sus datos para el envío de comunicados comerciales por correo electrónico, en relación a productos que consideramos que pueden ser de su interés.</p><br>
        <p><b>3.- Periodo de conservación de sus datos</b></p><br>
        <p>Depende del tratamiento de datos realizado:</p><br>
        <p>-Los datos relacionados con las  cookies existentes en este Sitio Web tienen un periodo de conservación indicado en la propia Política de Cookies.</p><br>
        <p>-Los datos que nos haga llegar a través de los medios que este Sitio Web pone a su disposición (formularios, correo electrónico, ventas realizadas) se conservarán mientras dure la relación con el interesado o el mismo nos retire su consentimiento en su caso. Posteriormente conservaremos los datos según exista o no obligación legal, siendo en cualquier caso el periodo mínimo exigido dependiendo de la relación o gestión que se realice. Por ejemplo, conservaremos los datos  de facturación por obligación legal tributaria y contable durante 6 años. Existe también el plazo de 5 años que establece el art. 1964 del Código Civil (acciones personales sin plazo especial).</p><br>
        <p>-Los datos incluídos en las redes sociales enlazadas a través del presente Sitio Web se mantendrán por nuestra parte hasta que el interesado retire su consentimiento. Sin embargo, es posible que las entidades responsables conserven estos datos según otras politicas de tratamiento de la que no nos hacemos responsables en ningún caso.</p><br>
        <p>-Los datos relacionados con el envío de comunicados comerciales se tratarán mientras Vd. no se opongo al tratamiento.</p><br>
        <p><b>4.- Legitimación para el tratamiento de sus datos.</b></p><br>
        <p>Depende del tratamiento de datos realizado:</p><br>
        <p>-La existencia de una o varias obligaciones legales que nos obligan al tratamiento. Por ejemplo, la mencionada obligación tributaria en relación a las facturas emitidas.</p><br>
        <p>-Nos ha dado el consentimiento para tratar sus datos en los términos expuestos, marcando la casilla de aceptación correspondiente en el proceso de registro. Es el caso del envío de comunicados comerciales.</p><br>
        <p>-Existe un interés legítimo para el tratamiento. Por ejemplo, en el caso de que el interesado nos proporcione sus datos en relación a una gestión encomendada, los trataremos porque entendemos que tenemos que dar cumplida respuesta a la misma.</p><br>
        <p>-Existe una relación contractual previa. Es el caso de la compra online de productos en nuestra tienda virtual. Adicionalmente le solicitaremos su consentimiento previo para proceder al tratamiento de sus datos. En su caso, le solicitaremos el consentimiento expreso para el tratamiento de sus datos de salud.</p><br>
        <p>5.- Destinatario de sus datos.</p><br>
        <p>Además del Responsable del Tratamiento arriba expuesto, los datos podrán tratarse por otras entidades dependiendo de la naturaleza del tratamiento de datos:</p><br>
        <p>-Las entidades responsables de las redes sociales enlazadas desde el presente sitio web, en caso de que  el interesado proporcione información a través de las mismas.</p><br>
        <p>-Determinadas empresas responsable de las cookies que se alojan en su equipo por el mero hecho de visitar el presente Sitio Web pueden tener información asociada a su dirección IP, hábitos de navegación, etc, según se describe en la correspondiente Política de Cookies.</p><br>
        <p>-Determinadas empresas de servicios relacionados con el presente Sitio Web. Por ejemplo, la entidad que nos presta servicios de hosting (alojamiento) y la entidad relacioanada con el transporte del producto o productos adquiridos.</p><br>
        <p>-Por obligación legal, la Agencia Española de Administración Tributaria también puede requerirnos información de trascendencia tributaria, teniendo por nuestra parte la obligación de proporcionársela.</p><br>
        <p><b>6.- Sus Derechos.</b></p><br>
        <p>Cualquier persona tiene derecho a obtener confirmación sobre si en esta entidad estamos tratando datos personales que les conciernan o no. Las personas interesadas tienen derecho a acceder a sus datos personales, así como a solicitar la rectificación de los datos inexactos o, en su caso, solicitar su supresión cuando, entre otros motivos, los datos ya no sean necesarios para los fines que fueron recogidos. En determinadas circunstancias, los interesados podrán solicitar la limitación del tratamiento de sus datos, en cuyo caso únicamente los conservaremos para el ejercicio o la defensa de reclamaciones. En otras circunstancias y por motivos relacionados con su situación particular, los interesados podrán oponerse al tratamiento de sus datos. En aquellos casos en los que nos haya dado el consentimiento, le informamos adicionalmente que tiene el derecho a retirar el mismo en cualquier momento, sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada. Si lo solicita, esta entidad dejará de tratar los datos, salvo por motivos legítimos imperiosos, o el ejercicio o la defensa de posibles reclamaciones. También puede requerirnos para que sus datos sean tratados por otra entidad, facilitando esta entidad la portabilidad de sus datos al nuevo responsable. Con tal fin, se han elaborado unos formularios específicos (que están a su disposición y que puede solicitar) para que pueda ejercitar sus derechos de acceso, rectificación, supresión, limitación al tratamiento, oposición al tratamiento, oposición a la toma de decisiones individuales automatizadas incluida la elaboración de perfiles y a la portabilidad de los datos. En todo caso, si considera que estos derechos no se han satisfecho convenientemente por nuestra parte, le informamos que puede presentar una reclamación ante la autoridad de control (Agencia Española de Protección de Datos, Jorge Juan 6, 28001, Madrid, o ante su sede electrónica https://sedeagpd.gob.es).</p><br>
        <p>Si lo prefiere, el interesado puede dirigirse por correo postal a la dirección que figura en el encabezamiento, o por correo electrónico en el email indicado, incluyendo fotocopia de su DNI/NIF o documento equivalente  para justificar su identidad y solicitar el ejercicio de los derechos arriba mencionados.</p><br>
        <p><b>7.- Especial referencia a redes sociales</b></p><br>
        <p>El Titular mantiene varias páginas y/o perfiles en varias redes sociales, enlazadas a través del presente Sitio Web. El Titular no será responsable de lo publicado por terceros en las mencionadas redes sociales. El uso y tratamiento de datos que terceros hagan en las mencionadas redes sociales estará sometido a las condiciones generales o particulares distintas a la presente. La Titular recomienda su atenta lectura y concienciación al respecto.</p><br>
        <p>Nuestra presencia en Internet incluye presencia en la red social facebook.com, operada por Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, EE. UU. ("Facebook"). Puede buscarnos en la mencionada red social y pulsar "me gusta" en la misma. Si ha iniciado sesión en Facebook, este podrá asignar la navegación a su cuenta de Facebook. Consulte la finalidad y el alcance de la recogida de datos y su procesamiento y uso por parte de Facebook, así como sus derechos al respecto y las posibilidades de configuración para proteger su privacidad en la declaración de privacidad de Facebook: http://www.facebook.com/policy.php</p><br>
        <p>En relación a la red social Google Plus, los datos serán tratados por Google, estando sometidos a política de privacidad de Google. Le recomendamos que lea la política de privacidad de esta entidad en https://www.google.com/intl/es_ALL/+/policy/.  Igual que la anterior red social, no utilizaremos los datos personales de los usuarios para finalidades diferentes a las señaladas en párrafos anteriores ni para enviarles información a través de un entorno diferente de la red social. Por el mero hecho de usar esta red social y comunicarse con nosotros, autoriza que sus datos personales los utilicemos únicamente a través de la plataforma de la mencionada red social con finalidades de gestión de nuestra página profesional que mantenemos en este red social y de las comunicaciones que mantengamos de forma bidireccional con nuestros seguidores a través del chat, mensajes u otros medios de comunicación que permita Google ahora y en el futuro. El Titular no se hace responsable de los tratamientos de datos que Google realice, estando ellos sometidos a la política de privacidad descrita en el mencionado enlace y por la que el Titular de esta página web no se hace responsable</p><br>
        <p>En cuanto a "Youtube", de la misma forma que en la anterior, si Vd nos proporciona cierta información en base a comentarios a las imágenes o vídeos, sus datos personales se tratarán bajo la política de privacidad de esta red social. Puede visitar al respecto la política de privacidad de Google (entidad responsable de esta plataforma de vídeo online) en:  http://www.youtube.com/static?gl=ES&template=terms&hl=es. De igual forma, los datos de los usuarios que hagan comentarios los utilizaremos únicamente para gestionar y responder los mensajes que intercambiaremos con los mismos.</p><br>
        <p>En relación a Twitter, cuando un usuario nos sigue pinchando el botón “Seguir”, tendremos acceso a la información de las personas que nos siguen, concretamente, el nombre de usuario, fotografía (en caso de que el usuario haya puesto una fotografía en su perfil), y comentarios o “Tweets” realizados así como al resto de la información que ha publicado en su perfil como por ejemplo usuarios a los que sigue y sus seguidores, aunque no utilizaremos dicha información. En especial, la información que el usuario da en su "biografía" puede ser accesible por nosotros. Al igual que en la anterior plataforma, es responsabilidad del usuario el uso que haga de la Red Social. Los datos de los usuarios que nos siguen en Twitter los utilizamos únicamente para gestionar y responder los “Tweets” o mensajes que intercambiamos con ellos. Puede consultar la política de privadad de Twitter en el siguiente enlace: https://twitter.com/privacy.</p><br>
        <p>En cuanto a la red social Instagram, la misma fué adquirida por Facebook. Puede revisar su política de privacidad en el siguiente enlace: https://help.instagram.com/519522125107875?helpref=page_content. En la medida en que uses esta red social (por ejemplo, comentando fotografias), esta entidad puede recabar datos personales, datos por los que El Titular de este Sitio Web ya no será responsable, y que estarán sometidos a otros términos y condiciones (le aconsejamos que visite el sitio web del enlace anteriormente citado). Por nuestra parte, salvo que avisemos previamente de lo contrario, no crearemos bases de datos específicas de usuarios que nos sigan a través de esta red social, y trataremos sus datos siempre dentro de la misma, por ejemplo limitándonos a contestar comentarios que nos hagan.</p><br>
        <p>Por lo que respecta a la red social Pinterest, su política de privacidad está accesible en https://policy.pinterest.com/es/privacy-policy. Del mismo modo que las anteriores, los datos de los usuarios que hagan comentarios los utilizaremos únicamente para gestionar y responder los mensajes que intercambiaremos con los mismos.</p><br><br>
        
    </div>


    <x-footer />
    <script src="{{ asset('js/desplegable.js') }}"></script>
</body>

</html>